baseURL: "https://dengya.ng/"
languageCode: en-us
title: "邓扬"
theme: "netlify-basic"
timeZone: "Asia/Shanghai" 
disableHugoGeneratorInject: true 
uglyURLs: true
permalinks:
  posts: /:slug/

params:
  mainSections: ["posts"]

mediaTypes:
  image/avif:
    suffixes:
      - avif

outputFormats:
  AVIF:
    mediaType: "image/avif"
    isPlainText: false
