baseURL: "https://dengya.ng/"
languageCode: "en-us"
title: "Deng Yang"
theme: "netlify-basic"
timeZone: "Asia/Shanghai" 
disableHugoGeneratorInject: true 
permalinks:
  posts: "/:slug.html"

params:
  mainSections: ["posts"]
