baseURL: "https://dengya.ng/"
languageCode: en-us
title: "Deng Yang"
theme: "netlify-basic"
timeZone: "Asia/Shanghai" 
disableHugoGeneratorInject: true 
uglyURLs: true

build:
  writeStats: true

ignoreFiles:
  - "\\.jpg$"
  - "\\.jpeg$"
  - "\\.png$"

permalinks:
  posts: /:slug/
  pages: /:slug/

params:
  mainSections: ["posts"]

menu:
  main:
    - name: "About"
      url: "/about/"
      weight: 10

mediaTypes:
  image/avif:
    suffixes:
      - avif

outputFormats:
  AVIF:
    mediaType: "image/avif"
    isPlainText: false

