baseURL: "https://dengya.ng/"
languageCode: "en-us"
title: "Deng Yang"
theme: "netlify-basic"
uglyURLs: true
timeZone: "Asia/Shanghai" 
disableHugoGeneratorInject: true 

params:
  mainSections: ["posts"]
