baseURL: "https://dengya.ng/"
languageCode: "zh-cn"
title: "Deng Yang"
theme: "DY"
timeZone: "Asia/Shanghai" 
disableHugoGeneratorInject: true 
uglyURLs: true

ignoreFiles:
  - "\\.jpg$"
  - "\\.jpeg$"
  - "\\.png$"

permalinks:
  posts: /:slug/
  pages: /:slug/

params:
  description: "专注于DevOps工程实践，分享自动化部署、持续集成和云原生技术"
  
  mainSections: ["posts"]

mediaTypes:
  image/avif:
    suffixes:
      - avif

outputFormats:
  AVIF:
    mediaType: "image/avif"
    isPlainText: false
