baseURL: "https://dengya.ng/"
languageCode: en-us
title: "Deng Yang"
theme: "DY"
timeZone: "Asia/Shanghai" 
disableHugoGeneratorInject: true 
uglyURLs: false

ignoreFiles:
  - "\\.jpg$"
  - "\\.jpeg$"
  - "\\.png$"

permalinks:
  posts: /:slug
  pages: /:slug

params:
  mainSections: ["posts"]

mediaTypes:
  image/avif:
    suffixes:
      - avif

outputFormats:
  AVIF:
    mediaType: "image/avif"
    isPlainText: false

