baseURL: "https://dengya.ng/"
languageCode: en-us
title: "Deng Yang"
theme: "netlify-basic"
timeZone: "Asia/Shanghai" 
disableHugoGeneratorInject: true 
uglyURLs: true
permalinks:
  posts: /:slug/

params:
  mainSections: ["posts"]
