# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "DY"
license = "MIT"
description = "A very basic theme for a quickstart template"
homepage = "http://hugo-quickstart.netlify.com"
tags = ["blog"]
features = []
min_version = "0.41.0"

[author]
  name = "Deng Yang"
  homepage = "https://dengya.ng/"

[original]
    author = "Netlify Template Team"
    homepage = "https://github.com/netlify-templates/hugo-quickstart"
    repo = "https://github.com/netlify-templates"
